apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: portfolio-app-stg-set
spec:
  generators:
  - list:
      elements:
        - cluster_url: 'https://C97142F25F1C99374E82B9D29D8F83A7.gr7.us-east-2.eks.amazonaws.com'
          environment: staging
          target_revision: HEAD
          namespace: web-app
          region: us-east-1
  template:
    metadata:
      name: portfolio-app-{{environment}}-{{region}}
    spec:
      destination:
        namespace: '{{namespace}}'
        server: '{{cluster_url}}'
      source:
        path: 'charts/portfolio-app'
        repoURL: 'https://github.com/Dhruvin4530/argoCD-Helm'
        targetRevision: '{{target_revision}}'
        helm:
          releaseName: portfolio-app
          valueFiles:
            - charts/portfolio-app/values/{{environment}}/values.yaml
      project: default
      syncPolicy: {}
    