apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: portfolio-app-dev-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster_url: 'https://E1AD8AA23D533C4F7577F7E5490B77F3.gr7.us-east-2.eks.amazonaws.com'
          environment: development
          target_revision: dev-application-v0.1
          namespace: mywebapp
          region: us-east-1
  template:
    metadata:
      name: portfolio-app-{{environment}}-{{region}}
    spec:
      destination:
        namespace: '{{namespace}}'
        server: '{{cluster_url}}'
      source:
        path: 'charts/portfolio-app'
        repoURL: 'https://github.com/Dhruvin4530/argoCD-Helm'
        targetRevision: '{{target_revision}}'
        helm:
          releaseName: portfolio-app
          valueFiles:
            - ./values/{{environment}}/values.yaml
      project: default
      syncPolicy: {}
