apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: portfolio-app-prod-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
          environment: production
          target_revision: HEAD
          namespace: mywebapp
          region: us-west-1
  template:
    metadata:
      name: portfolio-app-{{environment}}-{{region}}
    spec:
      destination:
        namespace: '{{namespace}}'
        server: 'https://kubernetes.default.svc'
      source:
        path: 'charts/portfolio-app'
        repoURL: 'https://github.com/yogeshhhh/argoCD-Helm'
        targetRevision: '{{target_revision}}'
        helm:
          releaseName: portfolio-app
          valueFiles:
            - ./values/{{environment}}/values.yamll
      project: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
